apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: koske-game
build:
  artifacts:
    - image: game-app
      docker:
        dockerfile: Dockerfile
    - image: my-api-image
      docker:
        dockerfile: api/Dockerfile
    - image: db-api
      docker:
        dockerfile: db/Dockerfile
manifests:
  rawYaml:
    - k8s/deployment.yml
    - k8s/service.yml
    - db-api.yaml
    - k8s/ingress.yml